// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assistente.sql

package db

import (
	"context"
	"time"
)

const assistenteCadastro = `-- name: AssistenteCadastro :one

SELECT (SELECT count(*) FROM clientes)::int                        AS clientes,
       (SELECT count(*) FROM cotas)::int                           AS cotas,
       (SELECT count(*) FROM cotas WHERE ativa)::int               AS cotas_ativas
`

type AssistenteCadastroRow struct {
	Clientes    int32
	Cotas       int32
	CotasAtivas int32
}

// Números do Canopus para o assistente da tela inicial (ferramenta resumo_canopus). Período
// opcional: sem desde/ate, o histórico inteiro.
func (q *Queries) AssistenteCadastro(ctx context.Context) (AssistenteCadastroRow, error) {
	row := q.db.QueryRow(ctx, assistenteCadastro)
	var i AssistenteCadastroRow
	err := row.Scan(&i.Clientes, &i.Cotas, &i.CotasAtivas)
	return i, err
}

const assistenteCotasPorStatus = `-- name: AssistenteCotasPorStatus :many
SELECT e.tipo, ec.status, count(*)::int AS quantidade
FROM execucao_cotas ec
JOIN execucoes e ON e.id = ec.execucao_id
WHERE e.criada_em >= coalesce($1::timestamptz, '-infinity')
  AND e.criada_em <  coalesce($2::timestamptz, 'infinity')
GROUP BY e.tipo, ec.status
ORDER BY e.tipo, ec.status
`

type AssistenteCotasPorStatusParams struct {
	Desde *time.Time
	Ate   *time.Time
}

type AssistenteCotasPorStatusRow struct {
	Tipo       string
	Status     string
	Quantidade int32
}

// Cotas processadas no período (pela data da execução).
func (q *Queries) AssistenteCotasPorStatus(ctx context.Context, arg AssistenteCotasPorStatusParams) ([]AssistenteCotasPorStatusRow, error) {
	rows, err := q.db.Query(ctx, assistenteCotasPorStatus, arg.Desde, arg.Ate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistenteCotasPorStatusRow
	for rows.Next() {
		var i AssistenteCotasPorStatusRow
		if err := rows.Scan(&i.Tipo, &i.Status, &i.Quantidade); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assistenteExecucoesPorTipo = `-- name: AssistenteExecucoesPorTipo :many
SELECT tipo, status, count(*)::int AS quantidade
FROM execucoes
WHERE criada_em >= coalesce($1::timestamptz, '-infinity')
  AND criada_em <  coalesce($2::timestamptz, 'infinity')
GROUP BY tipo, status
ORDER BY tipo, status
`

type AssistenteExecucoesPorTipoParams struct {
	Desde *time.Time
	Ate   *time.Time
}

type AssistenteExecucoesPorTipoRow struct {
	Tipo       string
	Status     string
	Quantidade int32
}

func (q *Queries) AssistenteExecucoesPorTipo(ctx context.Context, arg AssistenteExecucoesPorTipoParams) ([]AssistenteExecucoesPorTipoRow, error) {
	rows, err := q.db.Query(ctx, assistenteExecucoesPorTipo, arg.Desde, arg.Ate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistenteExecucoesPorTipoRow
	for rows.Next() {
		var i AssistenteExecucoesPorTipoRow
		if err := rows.Scan(&i.Tipo, &i.Status, &i.Quantidade); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assistenteLances = `-- name: AssistenteLances :one
SELECT count(*)::int                                                   AS total,
       (count(*) FILTER (WHERE origem = 'plataforma'))::int            AS pela_plataforma,
       (count(*) FILTER (WHERE origem = 'historico'))::int             AS do_historico,
       (count(*) FILTER (WHERE pdf_id IS NOT NULL))::int               AS com_pdf,
       (count(*) FILTER (WHERE drive_status = 'enviado'))::int         AS drive_enviados,
       (count(*) FILTER (WHERE drive_status IN ('pendente', 'enviando')))::int AS drive_na_fila,
       (count(*) FILTER (WHERE drive_status = 'erro'))::int            AS drive_com_erro,
       (count(*) FILTER (WHERE drive_status = 'nao_enviar'))::int      AS drive_nao_enviar,
       (count(*) FILTER (WHERE drive_status = 'sem_pdf'))::int         AS drive_sem_pdf
FROM lances
WHERE coalesce(registrado_em, criado_em) >= coalesce($1::timestamptz, '-infinity')
  AND coalesce(registrado_em, criado_em) <  coalesce($2::timestamptz, 'infinity')
`

type AssistenteLancesParams struct {
	Desde *time.Time
	Ate   *time.Time
}

type AssistenteLancesRow struct {
	Total          int32
	PelaPlataforma int32
	DoHistorico    int32
	ComPdf         int32
	DriveEnviados  int32
	DriveNaFila    int32
	DriveComErro   int32
	DriveNaoEnviar int32
	DriveSemPdf    int32
}

// Lances registrados no período (pela data de registro, ou de criação quando falta).
func (q *Queries) AssistenteLances(ctx context.Context, arg AssistenteLancesParams) (AssistenteLancesRow, error) {
	row := q.db.QueryRow(ctx, assistenteLances, arg.Desde, arg.Ate)
	var i AssistenteLancesRow
	err := row.Scan(
		&i.Total,
		&i.PelaPlataforma,
		&i.DoHistorico,
		&i.ComPdf,
		&i.DriveEnviados,
		&i.DriveNaFila,
		&i.DriveComErro,
		&i.DriveNaoEnviar,
		&i.DriveSemPdf,
	)
	return i, err
}

const assistenteUltimasExecucoes = `-- name: AssistenteUltimasExecucoes :many
SELECT e.id, e.tipo, e.status, e.criada_em, e.iniciada_em, e.finalizada_em, e.erro,
       u.nome AS criada_por,
       (SELECT count(*) FROM execucao_cotas ec WHERE ec.execucao_id = e.id)::int AS cotas,
       (SELECT count(*) FROM execucao_cotas ec WHERE ec.execucao_id = e.id
          AND ec.status IN ('erro_antes_confirmar', 'erro_apos_confirmar'))::int  AS cotas_com_erro
FROM execucoes e
JOIN usuarios u ON u.id = e.criada_por
ORDER BY e.id DESC
LIMIT 10
`

type AssistenteUltimasExecucoesRow struct {
	ID           int64
	Tipo         string
	Status       string
	CriadaEm     time.Time
	IniciadaEm   *time.Time
	FinalizadaEm *time.Time
	Erro         *string
	CriadaPor    string
	Cotas        int32
	CotasComErro int32
}

func (q *Queries) AssistenteUltimasExecucoes(ctx context.Context) ([]AssistenteUltimasExecucoesRow, error) {
	rows, err := q.db.Query(ctx, assistenteUltimasExecucoes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssistenteUltimasExecucoesRow
	for rows.Next() {
		var i AssistenteUltimasExecucoesRow
		if err := rows.Scan(
			&i.ID,
			&i.Tipo,
			&i.Status,
			&i.CriadaEm,
			&i.IniciadaEm,
			&i.FinalizadaEm,
			&i.Erro,
			&i.CriadaPor,
			&i.Cotas,
			&i.CotasComErro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
