// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clientes.sql

package db

import (
	"context"
	"time"
)

const atualizarContatoCliente = `-- name: AtualizarContatoCliente :exec
UPDATE clientes
SET telefone      = COALESCE($1, telefone),
    email         = COALESCE($2, email),
    atualizado_em = now()
WHERE id = $3
`

type AtualizarContatoClienteParams struct {
	Telefone *string
	Email    *string
	ID       int64
}

// Telefone/e-mail vazios na planilha não apagam o que já está no cadastro.
func (q *Queries) AtualizarContatoCliente(ctx context.Context, arg AtualizarContatoClienteParams) error {
	_, err := q.db.Exec(ctx, atualizarContatoCliente, arg.Telefone, arg.Email, arg.ID)
	return err
}

const buscarCliente = `-- name: BuscarCliente :one
SELECT id, nome, telefone, email, origem, criado_em, atualizado_em
FROM clientes
WHERE id = $1
`

type BuscarClienteRow struct {
	ID           int64
	Nome         string
	Telefone     *string
	Email        *string
	Origem       string
	CriadoEm     time.Time
	AtualizadoEm time.Time
}

func (q *Queries) BuscarCliente(ctx context.Context, id int64) (BuscarClienteRow, error) {
	row := q.db.QueryRow(ctx, buscarCliente, id)
	var i BuscarClienteRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Telefone,
		&i.Email,
		&i.Origem,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const criarCliente = `-- name: CriarCliente :one
INSERT INTO clientes (nome, nome_normalizado, telefone, email, origem)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CriarClienteParams struct {
	Nome            string
	NomeNormalizado string
	Telefone        *string
	Email           *string
	Origem          string
}

func (q *Queries) CriarCliente(ctx context.Context, arg CriarClienteParams) (int64, error) {
	row := q.db.QueryRow(ctx, criarCliente,
		arg.Nome,
		arg.NomeNormalizado,
		arg.Telefone,
		arg.Email,
		arg.Origem,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listarClientes = `-- name: ListarClientes :many
SELECT c.id, c.nome, c.telefone, c.email,
       count(q.id)::int                          AS total_cotas,
       (count(q.id) FILTER (WHERE q.ativa))::int AS cotas_ativas
FROM clientes c
LEFT JOIN cotas q ON q.cliente_id = c.id
WHERE $1::text IS NULL
   OR c.nome ILIKE '%' || $1::text || '%'
GROUP BY c.id
ORDER BY c.nome
`

type ListarClientesRow struct {
	ID          int64
	Nome        string
	Telefone    *string
	Email       *string
	TotalCotas  int32
	CotasAtivas int32
}

func (q *Queries) ListarClientes(ctx context.Context, busca *string) ([]ListarClientesRow, error) {
	rows, err := q.db.Query(ctx, listarClientes, busca)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarClientesRow
	for rows.Next() {
		var i ListarClientesRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Telefone,
			&i.Email,
			&i.TotalCotas,
			&i.CotasAtivas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarClientesParaImportacao = `-- name: ListarClientesParaImportacao :many
SELECT id, nome, nome_normalizado, telefone, email
FROM clientes
`

type ListarClientesParaImportacaoRow struct {
	ID              int64
	Nome            string
	NomeNormalizado string
	Telefone        *string
	Email           *string
}

func (q *Queries) ListarClientesParaImportacao(ctx context.Context) ([]ListarClientesParaImportacaoRow, error) {
	rows, err := q.db.Query(ctx, listarClientesParaImportacao)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarClientesParaImportacaoRow
	for rows.Next() {
		var i ListarClientesParaImportacaoRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.NomeNormalizado,
			&i.Telefone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
