// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: configuracao.sql

package db

import (
	"context"
	"time"
)

const atualizarConfiguracaoCanopus = `-- name: AtualizarConfiguracaoCanopus :exec
UPDATE configuracao_canopus SET
    dry_run_automatico        = $1,
    dry_run_dia               = $2,
    dry_run_hora              = $3,
    dry_run_minuto            = $4,
    aviso_email               = $5,
    drive_pasta_id            = $6,
    validade_dry_run_minutos  = $7,
    retencao_screenshots_dias = $8,
    atualizado_por            = $9,
    atualizado_em             = now()
WHERE id
`

type AtualizarConfiguracaoCanopusParams struct {
	DryRunAutomatico        bool
	DryRunDia               int16
	DryRunHora              int16
	DryRunMinuto            int16
	AvisoEmail              bool
	DrivePastaID            *string
	ValidadeDryRunMinutos   int32
	RetencaoScreenshotsDias int32
	AtualizadoPor           *int64
}

func (q *Queries) AtualizarConfiguracaoCanopus(ctx context.Context, arg AtualizarConfiguracaoCanopusParams) error {
	_, err := q.db.Exec(ctx, atualizarConfiguracaoCanopus,
		arg.DryRunAutomatico,
		arg.DryRunDia,
		arg.DryRunHora,
		arg.DryRunMinuto,
		arg.AvisoEmail,
		arg.DrivePastaID,
		arg.ValidadeDryRunMinutos,
		arg.RetencaoScreenshotsDias,
		arg.AtualizadoPor,
	)
	return err
}

const buscarConfiguracaoCanopus = `-- name: BuscarConfiguracaoCanopus :one
SELECT c.id, c.dry_run_automatico, c.dry_run_dia, c.dry_run_hora, c.dry_run_minuto, c.aviso_email, c.drive_pasta_id, c.validade_dry_run_minutos, c.retencao_screenshots_dias, c.atualizado_por, c.atualizado_em, u.nome AS atualizado_por_nome
FROM configuracao_canopus c
LEFT JOIN usuarios u ON u.id = c.atualizado_por
WHERE c.id
`

type BuscarConfiguracaoCanopusRow struct {
	ID                      bool
	DryRunAutomatico        bool
	DryRunDia               int16
	DryRunHora              int16
	DryRunMinuto            int16
	AvisoEmail              bool
	DrivePastaID            *string
	ValidadeDryRunMinutos   int32
	RetencaoScreenshotsDias int32
	AtualizadoPor           *int64
	AtualizadoEm            time.Time
	AtualizadoPorNome       *string
}

func (q *Queries) BuscarConfiguracaoCanopus(ctx context.Context) (BuscarConfiguracaoCanopusRow, error) {
	row := q.db.QueryRow(ctx, buscarConfiguracaoCanopus)
	var i BuscarConfiguracaoCanopusRow
	err := row.Scan(
		&i.ID,
		&i.DryRunAutomatico,
		&i.DryRunDia,
		&i.DryRunHora,
		&i.DryRunMinuto,
		&i.AvisoEmail,
		&i.DrivePastaID,
		&i.ValidadeDryRunMinutos,
		&i.RetencaoScreenshotsDias,
		&i.AtualizadoPor,
		&i.AtualizadoEm,
		&i.AtualizadoPorNome,
	)
	return i, err
}

const garantirConfiguracaoCanopus = `-- name: GarantirConfiguracaoCanopus :exec

INSERT INTO configuracao_canopus (id) VALUES (true) ON CONFLICT (id) DO NOTHING
`

// Configuração do serviço Canopus: uma linha só, criada pela migração 00012.
func (q *Queries) GarantirConfiguracaoCanopus(ctx context.Context) error {
	_, err := q.db.Exec(ctx, garantirConfiguracaoCanopus)
	return err
}
