// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cotas.sql

package db

import (
	"context"
	"time"
)

const atualizarCotaImportada = `-- name: AtualizarCotaImportada :exec
UPDATE cotas
SET cliente_id     = $1,
    tipo_consorcio = $2,
    dados_planilha = $3,
    importacao_id  = $4,
    atualizado_em  = now()
WHERE id = $5
`

type AtualizarCotaImportadaParams struct {
	ClienteID     int64
	TipoConsorcio *string
	DadosPlanilha []byte
	ImportacaoID  *int64
	ID            int64
}

func (q *Queries) AtualizarCotaImportada(ctx context.Context, arg AtualizarCotaImportadaParams) error {
	_, err := q.db.Exec(ctx, atualizarCotaImportada,
		arg.ClienteID,
		arg.TipoConsorcio,
		arg.DadosPlanilha,
		arg.ImportacaoID,
		arg.ID,
	)
	return err
}

const definirCotaAtiva = `-- name: DefinirCotaAtiva :one
UPDATE cotas
SET ativa = $1, atualizado_em = now()
WHERE id = $2
RETURNING id, grupo, cota, versao, ativa
`

type DefinirCotaAtivaParams struct {
	Ativa bool
	ID    int64
}

type DefinirCotaAtivaRow struct {
	ID     int64
	Grupo  string
	Cota   string
	Versao string
	Ativa  bool
}

func (q *Queries) DefinirCotaAtiva(ctx context.Context, arg DefinirCotaAtivaParams) (DefinirCotaAtivaRow, error) {
	row := q.db.QueryRow(ctx, definirCotaAtiva, arg.Ativa, arg.ID)
	var i DefinirCotaAtivaRow
	err := row.Scan(
		&i.ID,
		&i.Grupo,
		&i.Cota,
		&i.Versao,
		&i.Ativa,
	)
	return i, err
}

const inserirCota = `-- name: InserirCota :one
INSERT INTO cotas (cliente_id, administradora, grupo, cota, versao, tipo_consorcio, dados_planilha, importacao_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InserirCotaParams struct {
	ClienteID      int64
	Administradora string
	Grupo          string
	Cota           string
	Versao         string
	TipoConsorcio  *string
	DadosPlanilha  []byte
	ImportacaoID   *int64
}

func (q *Queries) InserirCota(ctx context.Context, arg InserirCotaParams) (int64, error) {
	row := q.db.QueryRow(ctx, inserirCota,
		arg.ClienteID,
		arg.Administradora,
		arg.Grupo,
		arg.Cota,
		arg.Versao,
		arg.TipoConsorcio,
		arg.DadosPlanilha,
		arg.ImportacaoID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listarCotas = `-- name: ListarCotas :many
SELECT q.id, q.cliente_id, c.nome AS cliente_nome, q.administradora, q.grupo, q.cota, q.versao,
       q.tipo_consorcio, q.modalidade_padrao, q.ativa, q.atualizado_em
FROM cotas q
JOIN clientes c ON c.id = q.cliente_id
WHERE ($1::bigint IS NULL OR q.cliente_id = $1::bigint)
  AND ($2::text IS NULL OR q.grupo = $2::text)
  AND ($3::boolean IS NULL OR q.ativa = $3::boolean)
  AND ($4::text IS NULL
       OR c.nome ILIKE '%' || $4::text || '%'
       OR q.grupo LIKE '%' || $4::text || '%'
       OR q.cota LIKE '%' || $4::text || '%')
ORDER BY c.nome, q.grupo, q.cota, q.versao
`

type ListarCotasParams struct {
	ClienteID *int64
	Grupo     *string
	Ativa     *bool
	Busca     *string
}

type ListarCotasRow struct {
	ID               int64
	ClienteID        int64
	ClienteNome      string
	Administradora   string
	Grupo            string
	Cota             string
	Versao           string
	TipoConsorcio    *string
	ModalidadePadrao string
	Ativa            bool
	AtualizadoEm     time.Time
}

func (q *Queries) ListarCotas(ctx context.Context, arg ListarCotasParams) ([]ListarCotasRow, error) {
	rows, err := q.db.Query(ctx, listarCotas,
		arg.ClienteID,
		arg.Grupo,
		arg.Ativa,
		arg.Busca,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarCotasRow
	for rows.Next() {
		var i ListarCotasRow
		if err := rows.Scan(
			&i.ID,
			&i.ClienteID,
			&i.ClienteNome,
			&i.Administradora,
			&i.Grupo,
			&i.Cota,
			&i.Versao,
			&i.TipoConsorcio,
			&i.ModalidadePadrao,
			&i.Ativa,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarCotasParaImportacao = `-- name: ListarCotasParaImportacao :many
SELECT q.id, q.cliente_id, c.nome AS cliente_nome, c.nome_normalizado AS cliente_nome_normalizado,
       q.administradora, q.grupo, q.cota, q.versao, q.tipo_consorcio, q.ativa, q.dados_planilha
FROM cotas q
JOIN clientes c ON c.id = q.cliente_id
ORDER BY q.administradora, q.grupo, q.cota, q.versao
`

type ListarCotasParaImportacaoRow struct {
	ID                     int64
	ClienteID              int64
	ClienteNome            string
	ClienteNomeNormalizado string
	Administradora         string
	Grupo                  string
	Cota                   string
	Versao                 string
	TipoConsorcio          *string
	Ativa                  bool
	DadosPlanilha          []byte
}

func (q *Queries) ListarCotasParaImportacao(ctx context.Context) ([]ListarCotasParaImportacaoRow, error) {
	rows, err := q.db.Query(ctx, listarCotasParaImportacao)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarCotasParaImportacaoRow
	for rows.Next() {
		var i ListarCotasParaImportacaoRow
		if err := rows.Scan(
			&i.ID,
			&i.ClienteID,
			&i.ClienteNome,
			&i.ClienteNomeNormalizado,
			&i.Administradora,
			&i.Grupo,
			&i.Cota,
			&i.Versao,
			&i.TipoConsorcio,
			&i.Ativa,
			&i.DadosPlanilha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarGrupos = `-- name: ListarGrupos :many
SELECT DISTINCT grupo FROM cotas ORDER BY grupo
`

func (q *Queries) ListarGrupos(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listarGrupos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var grupo string
		if err := rows.Scan(&grupo); err != nil {
			return nil, err
		}
		items = append(items, grupo)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
