// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execucoes.sql

package db

import (
	"context"
	"time"
)

const apagarArquivosExpirados = `-- name: ApagarArquivosExpirados :execrows
DELETE FROM arquivos WHERE expira_em < now()
`

func (q *Queries) ApagarArquivosExpirados(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, apagarArquivosExpirados)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const buscarArquivo = `-- name: BuscarArquivo :one
SELECT id, tipo, nome, content_type, tamanho, conteudo, criado_em
FROM arquivos
WHERE id = $1
`

type BuscarArquivoRow struct {
	ID          string
	Tipo        string
	Nome        string
	ContentType string
	Tamanho     int32
	Conteudo    []byte
	CriadoEm    time.Time
}

func (q *Queries) BuscarArquivo(ctx context.Context, id string) (BuscarArquivoRow, error) {
	row := q.db.QueryRow(ctx, buscarArquivo, id)
	var i BuscarArquivoRow
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Nome,
		&i.ContentType,
		&i.Tamanho,
		&i.Conteudo,
		&i.CriadoEm,
	)
	return i, err
}

const buscarExecucao = `-- name: BuscarExecucao :one
SELECT e.id, e.tipo, e.status, e.criada_em, e.iniciada_em, e.finalizada_em, e.cancelamento_solicitado, e.erro,
       u.nome AS criada_por_nome, uc.nome AS cancelada_por_nome
FROM execucoes e
JOIN usuarios u ON u.id = e.criada_por
LEFT JOIN usuarios uc ON uc.id = e.cancelada_por
WHERE e.id = $1
`

type BuscarExecucaoRow struct {
	ID                     int64
	Tipo                   string
	Status                 string
	CriadaEm               time.Time
	IniciadaEm             *time.Time
	FinalizadaEm           *time.Time
	CancelamentoSolicitado bool
	Erro                   *string
	CriadaPorNome          string
	CanceladaPorNome       *string
}

func (q *Queries) BuscarExecucao(ctx context.Context, id int64) (BuscarExecucaoRow, error) {
	row := q.db.QueryRow(ctx, buscarExecucao, id)
	var i BuscarExecucaoRow
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Status,
		&i.CriadaEm,
		&i.IniciadaEm,
		&i.FinalizadaEm,
		&i.CancelamentoSolicitado,
		&i.Erro,
		&i.CriadaPorNome,
		&i.CanceladaPorNome,
	)
	return i, err
}

const buscarExecucaoCotaParaWorker = `-- name: BuscarExecucaoCotaParaWorker :one
SELECT ec.id, ec.execucao_id, ec.status, ec.grupo, ec.cota, ec.versao,
       e.tipo, e.status AS execucao_status, e.worker, e.cancelamento_solicitado
FROM execucao_cotas ec
JOIN execucoes e ON e.id = ec.execucao_id
WHERE ec.id = $1
FOR UPDATE OF e
`

type BuscarExecucaoCotaParaWorkerRow struct {
	ID                     int64
	ExecucaoID             int64
	Status                 string
	Grupo                  string
	Cota                   string
	Versao                 string
	Tipo                   string
	ExecucaoStatus         string
	Worker                 *string
	CancelamentoSolicitado bool
}

func (q *Queries) BuscarExecucaoCotaParaWorker(ctx context.Context, id int64) (BuscarExecucaoCotaParaWorkerRow, error) {
	row := q.db.QueryRow(ctx, buscarExecucaoCotaParaWorker, id)
	var i BuscarExecucaoCotaParaWorkerRow
	err := row.Scan(
		&i.ID,
		&i.ExecucaoID,
		&i.Status,
		&i.Grupo,
		&i.Cota,
		&i.Versao,
		&i.Tipo,
		&i.ExecucaoStatus,
		&i.Worker,
		&i.CancelamentoSolicitado,
	)
	return i, err
}

const cancelarCotasPendentes = `-- name: CancelarCotasPendentes :execrows
UPDATE execucao_cotas
SET status = 'cancelada', finalizada_em = now()
WHERE execucao_id = $1 AND status = 'pendente'
`

func (q *Queries) CancelarCotasPendentes(ctx context.Context, execucaoID int64) (int64, error) {
	result, err := q.db.Exec(ctx, cancelarCotasPendentes, execucaoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelarExecucaoNaFila = `-- name: CancelarExecucaoNaFila :exec
UPDATE execucoes
SET status = 'cancelada', cancelamento_solicitado = true, cancelada_por = $1, finalizada_em = now()
WHERE id = $2
`

type CancelarExecucaoNaFilaParams struct {
	UsuarioID *int64
	ID        int64
}

func (q *Queries) CancelarExecucaoNaFila(ctx context.Context, arg CancelarExecucaoNaFilaParams) error {
	_, err := q.db.Exec(ctx, cancelarExecucaoNaFila, arg.UsuarioID, arg.ID)
	return err
}

const concluirExecucaoCota = `-- name: ConcluirExecucaoCota :execrows
UPDATE execucao_cotas
SET status = $1, erro_tipo = $2, erro = $3, detalhes = $4, finalizada_em = now()
WHERE id = $5 AND status = 'em_andamento'
`

type ConcluirExecucaoCotaParams struct {
	Status   string
	ErroTipo *string
	Erro     *string
	Detalhes []byte
	ID       int64
}

func (q *Queries) ConcluirExecucaoCota(ctx context.Context, arg ConcluirExecucaoCotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, concluirExecucaoCota,
		arg.Status,
		arg.ErroTipo,
		arg.Erro,
		arg.Detalhes,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const criarExecucao = `-- name: CriarExecucao :one

INSERT INTO execucoes (tipo, criada_por)
VALUES ($1, $2)
RETURNING id, tipo, status, criada_em
`

type CriarExecucaoParams struct {
	Tipo      string
	CriadaPor int64
}

type CriarExecucaoRow struct {
	ID       int64
	Tipo     string
	Status   string
	CriadaEm time.Time
}

// ===== Tela (usuário logado) =====
func (q *Queries) CriarExecucao(ctx context.Context, arg CriarExecucaoParams) (CriarExecucaoRow, error) {
	row := q.db.QueryRow(ctx, criarExecucao, arg.Tipo, arg.CriadaPor)
	var i CriarExecucaoRow
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Status,
		&i.CriadaEm,
	)
	return i, err
}

const definirScreenshotExecucaoCota = `-- name: DefinirScreenshotExecucaoCota :exec
UPDATE execucao_cotas SET screenshot_id = $1 WHERE id = $2
`

type DefinirScreenshotExecucaoCotaParams struct {
	ScreenshotID *string
	ID           int64
}

func (q *Queries) DefinirScreenshotExecucaoCota(ctx context.Context, arg DefinirScreenshotExecucaoCotaParams) error {
	_, err := q.db.Exec(ctx, definirScreenshotExecucaoCota, arg.ScreenshotID, arg.ID)
	return err
}

const devolverCotasEmAndamento = `-- name: DevolverCotasEmAndamento :execrows
UPDATE execucao_cotas
SET status = 'pendente'
WHERE execucao_id = $1 AND status = 'em_andamento'
`

func (q *Queries) DevolverCotasEmAndamento(ctx context.Context, execucaoID int64) (int64, error) {
	result, err := q.db.Exec(ctx, devolverCotasEmAndamento, execucaoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const devolverExecucaoParaFila = `-- name: DevolverExecucaoParaFila :execrows
UPDATE execucoes
SET status = 'na_fila', worker = NULL, trava_ate = NULL
WHERE id = $1 AND worker = $2 AND status = 'em_andamento'
`

type DevolverExecucaoParaFilaParams struct {
	ID     int64
	Worker *string
}

// SIGTERM no worker: termina a cota atual e devolve a execução para a fila.
func (q *Queries) DevolverExecucaoParaFila(ctx context.Context, arg DevolverExecucaoParaFilaParams) (int64, error) {
	result, err := q.db.Exec(ctx, devolverExecucaoParaFila, arg.ID, arg.Worker)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const devolverExecucoesComTravaVencida = `-- name: DevolverExecucoesComTravaVencida :many
UPDATE execucoes
SET status        = CASE WHEN cancelamento_solicitado THEN 'cancelada' ELSE 'na_fila' END,
    finalizada_em = CASE WHEN cancelamento_solicitado THEN now() END,
    worker        = NULL,
    trava_ate     = NULL
WHERE status = 'em_andamento' AND trava_ate < now()
RETURNING id, status
`

type DevolverExecucoesComTravaVencidaRow struct {
	ID     int64
	Status string
}

func (q *Queries) DevolverExecucoesComTravaVencida(ctx context.Context) ([]DevolverExecucoesComTravaVencidaRow, error) {
	rows, err := q.db.Query(ctx, devolverExecucoesComTravaVencida)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DevolverExecucoesComTravaVencidaRow
	for rows.Next() {
		var i DevolverExecucoesComTravaVencidaRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finalizarExecucao = `-- name: FinalizarExecucao :exec
UPDATE execucoes
SET status = $1, erro = $2, finalizada_em = now(), trava_ate = NULL
WHERE id = $3
`

type FinalizarExecucaoParams struct {
	Status string
	Erro   *string
	ID     int64
}

func (q *Queries) FinalizarExecucao(ctx context.Context, arg FinalizarExecucaoParams) error {
	_, err := q.db.Exec(ctx, finalizarExecucao, arg.Status, arg.Erro, arg.ID)
	return err
}

const iniciarExecucaoCota = `-- name: IniciarExecucaoCota :execrows
UPDATE execucao_cotas
SET status = 'em_andamento', tentativas = tentativas + 1, iniciada_em = now(),
    finalizada_em = NULL, erro = NULL, erro_tipo = NULL
WHERE id = $1 AND status IN ('pendente', 'erro_antes_confirmar')
`

func (q *Queries) IniciarExecucaoCota(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, iniciarExecucaoCota, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const inserirArquivo = `-- name: InserirArquivo :one
INSERT INTO arquivos (tipo, nome, content_type, tamanho, sha256, conteudo, expira_em)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InserirArquivoParams struct {
	Tipo        string
	Nome        string
	ContentType string
	Tamanho     int32
	Sha256      string
	Conteudo    []byte
	ExpiraEm    *time.Time
}

func (q *Queries) InserirArquivo(ctx context.Context, arg InserirArquivoParams) (string, error) {
	row := q.db.QueryRow(ctx, inserirArquivo,
		arg.Tipo,
		arg.Nome,
		arg.ContentType,
		arg.Tamanho,
		arg.Sha256,
		arg.Conteudo,
		arg.ExpiraEm,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const inserirCotasNaExecucao = `-- name: InserirCotasNaExecucao :execrows
INSERT INTO execucao_cotas (execucao_id, cota_id, ordem, grupo, cota, versao, cliente_nome, modalidade)
SELECT $1::bigint, q.id,
       (row_number() OVER (ORDER BY c.nome, q.grupo, q.cota, q.versao))::int,
       q.grupo, q.cota, q.versao, c.nome, q.modalidade_padrao
FROM cotas q
JOIN clientes c ON c.id = q.cliente_id
WHERE q.id = ANY($2::bigint[]) AND q.ativa
`

type InserirCotasNaExecucaoParams struct {
	ExecucaoID int64
	CotaIds    []int64
}

// Só cotas ativas entram. Ordem: cliente, grupo, cota, versão.
func (q *Queries) InserirCotasNaExecucao(ctx context.Context, arg InserirCotasNaExecucaoParams) (int64, error) {
	result, err := q.db.Exec(ctx, inserirCotasNaExecucao, arg.ExecucaoID, arg.CotaIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const inserirEvento = `-- name: InserirEvento :one
INSERT INTO execucao_eventos (execucao_id, execucao_cota_id, nivel, mensagem, dados)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InserirEventoParams struct {
	ExecucaoID     int64
	ExecucaoCotaID *int64
	Nivel          string
	Mensagem       string
	Dados          []byte
}

func (q *Queries) InserirEvento(ctx context.Context, arg InserirEventoParams) (int64, error) {
	row := q.db.QueryRow(ctx, inserirEvento,
		arg.ExecucaoID,
		arg.ExecucaoCotaID,
		arg.Nivel,
		arg.Mensagem,
		arg.Dados,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listarCotasDaExecucao = `-- name: ListarCotasDaExecucao :many
SELECT id, cota_id, ordem, grupo, cota, versao, cliente_nome, modalidade, status, erro_tipo, erro,
       detalhes, screenshot_id, tentativas, iniciada_em, finalizada_em
FROM execucao_cotas
WHERE execucao_id = $1
ORDER BY ordem
`

type ListarCotasDaExecucaoRow struct {
	ID           int64
	CotaID       int64
	Ordem        int32
	Grupo        string
	Cota         string
	Versao       string
	ClienteNome  string
	Modalidade   string
	Status       string
	ErroTipo     *string
	Erro         *string
	Detalhes     []byte
	ScreenshotID *string
	Tentativas   int32
	IniciadaEm   *time.Time
	FinalizadaEm *time.Time
}

func (q *Queries) ListarCotasDaExecucao(ctx context.Context, execucaoID int64) ([]ListarCotasDaExecucaoRow, error) {
	rows, err := q.db.Query(ctx, listarCotasDaExecucao, execucaoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarCotasDaExecucaoRow
	for rows.Next() {
		var i ListarCotasDaExecucaoRow
		if err := rows.Scan(
			&i.ID,
			&i.CotaID,
			&i.Ordem,
			&i.Grupo,
			&i.Cota,
			&i.Versao,
			&i.ClienteNome,
			&i.Modalidade,
			&i.Status,
			&i.ErroTipo,
			&i.Erro,
			&i.Detalhes,
			&i.ScreenshotID,
			&i.Tentativas,
			&i.IniciadaEm,
			&i.FinalizadaEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarEventos = `-- name: ListarEventos :many
SELECT id, execucao_cota_id, nivel, mensagem, dados, criado_em
FROM execucao_eventos
WHERE execucao_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListarEventosParams struct {
	ExecucaoID int64
	AposID     int64
	Limite     int32
}

type ListarEventosRow struct {
	ID             int64
	ExecucaoCotaID *int64
	Nivel          string
	Mensagem       string
	Dados          []byte
	CriadoEm       time.Time
}

func (q *Queries) ListarEventos(ctx context.Context, arg ListarEventosParams) ([]ListarEventosRow, error) {
	rows, err := q.db.Query(ctx, listarEventos, arg.ExecucaoID, arg.AposID, arg.Limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarEventosRow
	for rows.Next() {
		var i ListarEventosRow
		if err := rows.Scan(
			&i.ID,
			&i.ExecucaoCotaID,
			&i.Nivel,
			&i.Mensagem,
			&i.Dados,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarExecucoes = `-- name: ListarExecucoes :many
SELECT e.id, e.tipo, e.status, e.criada_em, e.iniciada_em, e.finalizada_em, e.cancelamento_solicitado, e.erro,
       u.nome                                                                                    AS criada_por_nome,
       count(ec.id)::int                                                                         AS total,
       (count(ec.id) FILTER (WHERE ec.status IN ('verificada', 'confirmada')))::int              AS sucesso,
       (count(ec.id) FILTER (WHERE ec.status IN ('erro_antes_confirmar', 'erro_apos_confirmar')))::int AS com_erro,
       (count(ec.id) FILTER (WHERE ec.status IN ('pendente', 'em_andamento')))::int              AS restantes
FROM execucoes e
JOIN usuarios u ON u.id = e.criada_por
LEFT JOIN execucao_cotas ec ON ec.execucao_id = e.id
GROUP BY e.id, u.nome
ORDER BY e.criada_em DESC
LIMIT 50
`

type ListarExecucoesRow struct {
	ID                     int64
	Tipo                   string
	Status                 string
	CriadaEm               time.Time
	IniciadaEm             *time.Time
	FinalizadaEm           *time.Time
	CancelamentoSolicitado bool
	Erro                   *string
	CriadaPorNome          string
	Total                  int32
	Sucesso                int32
	ComErro                int32
	Restantes              int32
}

func (q *Queries) ListarExecucoes(ctx context.Context) ([]ListarExecucoesRow, error) {
	rows, err := q.db.Query(ctx, listarExecucoes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarExecucoesRow
	for rows.Next() {
		var i ListarExecucoesRow
		if err := rows.Scan(
			&i.ID,
			&i.Tipo,
			&i.Status,
			&i.CriadaEm,
			&i.IniciadaEm,
			&i.FinalizadaEm,
			&i.CancelamentoSolicitado,
			&i.Erro,
			&i.CriadaPorNome,
			&i.Total,
			&i.Sucesso,
			&i.ComErro,
			&i.Restantes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const posicaoNaFila = `-- name: PosicaoNaFila :one
SELECT count(*)::int
FROM execucoes o, execucoes e
WHERE e.id = $1 AND o.status = 'na_fila' AND (o.criada_em, o.id) <= (e.criada_em, e.id)
`

func (q *Queries) PosicaoNaFila(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, posicaoNaFila, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const recuperarCotasDeTravasVencidas = `-- name: RecuperarCotasDeTravasVencidas :execrows

UPDATE execucao_cotas ec
SET status    = CASE WHEN ec.status = 'em_andamento' THEN 'pendente' ELSE 'erro_apos_confirmar' END,
    erro_tipo = CASE WHEN ec.status = 'em_andamento' THEN NULL ELSE 'inesperado' END,
    erro      = CASE WHEN ec.status = 'em_andamento' THEN NULL
                     ELSE 'o worker parou depois de iniciar a confirmação: o lance pode ter sido registrado, confira no Histórico' END
FROM execucoes e
WHERE e.id = ec.execucao_id
  AND e.status = 'em_andamento' AND e.trava_ate < now()
  AND ec.status IN ('em_andamento', 'confirmacao_iniciada')
`

// ===== Worker (rotas internas) =====
// Worker caiu (trava vencida): cota em_andamento volta a pendente (a confirmação não
// tinha começado). Cota em confirmacao_iniciada NUNCA volta: vira erro_apos_confirmar.
func (q *Queries) RecuperarCotasDeTravasVencidas(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recuperarCotasDeTravasVencidas)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renovarTrava = `-- name: RenovarTrava :one
UPDATE execucoes
SET trava_ate = now() + interval '2 minutes'
WHERE id = $1 AND worker = $2 AND status = 'em_andamento'
RETURNING cancelamento_solicitado
`

type RenovarTravaParams struct {
	ID     int64
	Worker *string
}

func (q *Queries) RenovarTrava(ctx context.Context, arg RenovarTravaParams) (bool, error) {
	row := q.db.QueryRow(ctx, renovarTrava, arg.ID, arg.Worker)
	var cancelamento_solicitado bool
	err := row.Scan(&cancelamento_solicitado)
	return cancelamento_solicitado, err
}

const reservarProximaExecucao = `-- name: ReservarProximaExecucao :one
UPDATE execucoes
SET status = 'em_andamento', worker = $1, trava_ate = now() + interval '2 minutes',
    iniciada_em = COALESCE(iniciada_em, now())
WHERE id = (
    SELECT p.id
    FROM execucoes p
    WHERE p.status = 'na_fila' AND NOT p.cancelamento_solicitado AND p.tipo = ANY($2::text[])
      AND NOT EXISTS (SELECT 1 FROM execucoes o WHERE o.credencial = p.credencial AND o.status = 'em_andamento')
    ORDER BY p.criada_em, p.id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, tipo, credencial
`

type ReservarProximaExecucaoParams struct {
	Worker *string
	Tipos  []string
}

type ReservarProximaExecucaoRow struct {
	ID         int64
	Tipo       string
	Credencial string
}

func (q *Queries) ReservarProximaExecucao(ctx context.Context, arg ReservarProximaExecucaoParams) (ReservarProximaExecucaoRow, error) {
	row := q.db.QueryRow(ctx, reservarProximaExecucao, arg.Worker, arg.Tipos)
	var i ReservarProximaExecucaoRow
	err := row.Scan(&i.ID, &i.Tipo, &i.Credencial)
	return i, err
}

const resumoCotasDaExecucao = `-- name: ResumoCotasDaExecucao :one
SELECT (count(*) FILTER (WHERE status IN ('erro_antes_confirmar', 'erro_apos_confirmar')))::int AS com_erro,
       (count(*) FILTER (WHERE status IN ('pendente', 'em_andamento')))::int               AS restantes,
       (count(*) FILTER (WHERE status = 'confirmacao_iniciada'))::int                     AS em_confirmacao
FROM execucao_cotas
WHERE execucao_id = $1
`

type ResumoCotasDaExecucaoRow struct {
	ComErro       int32
	Restantes     int32
	EmConfirmacao int32
}

func (q *Queries) ResumoCotasDaExecucao(ctx context.Context, execucaoID int64) (ResumoCotasDaExecucaoRow, error) {
	row := q.db.QueryRow(ctx, resumoCotasDaExecucao, execucaoID)
	var i ResumoCotasDaExecucaoRow
	err := row.Scan(&i.ComErro, &i.Restantes, &i.EmConfirmacao)
	return i, err
}

const solicitarCancelamento = `-- name: SolicitarCancelamento :exec
UPDATE execucoes
SET cancelamento_solicitado = true, cancelada_por = $1
WHERE id = $2
`

type SolicitarCancelamentoParams struct {
	UsuarioID *int64
	ID        int64
}

// O worker vê o pedido ao iniciar a próxima cota ou ao renovar a trava.
func (q *Queries) SolicitarCancelamento(ctx context.Context, arg SolicitarCancelamentoParams) error {
	_, err := q.db.Exec(ctx, solicitarCancelamento, arg.UsuarioID, arg.ID)
	return err
}

const travarExecucao = `-- name: TravarExecucao :one
SELECT id, tipo, status, worker, cancelamento_solicitado
FROM execucoes
WHERE id = $1
FOR UPDATE
`

type TravarExecucaoRow struct {
	ID                     int64
	Tipo                   string
	Status                 string
	Worker                 *string
	CancelamentoSolicitado bool
}

func (q *Queries) TravarExecucao(ctx context.Context, id int64) (TravarExecucaoRow, error) {
	row := q.db.QueryRow(ctx, travarExecucao, id)
	var i TravarExecucaoRow
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Status,
		&i.Worker,
		&i.CancelamentoSolicitado,
	)
	return i, err
}
