// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: importacoes.sql

package db

import (
	"context"
	"time"
)

const buscarImportacao = `-- name: BuscarImportacao :one
SELECT i.id, i.criada_por, u.nome AS criada_por_nome, i.arquivo_nome, i.arquivo_sha256,
       i.status, i.previa, i.criada_em, i.finalizada_em
FROM importacoes i
JOIN usuarios u ON u.id = i.criada_por
WHERE i.id = $1
`

type BuscarImportacaoRow struct {
	ID            int64
	CriadaPor     int64
	CriadaPorNome string
	ArquivoNome   string
	ArquivoSha256 string
	Status        string
	Previa        []byte
	CriadaEm      time.Time
	FinalizadaEm  *time.Time
}

func (q *Queries) BuscarImportacao(ctx context.Context, id int64) (BuscarImportacaoRow, error) {
	row := q.db.QueryRow(ctx, buscarImportacao, id)
	var i BuscarImportacaoRow
	err := row.Scan(
		&i.ID,
		&i.CriadaPor,
		&i.CriadaPorNome,
		&i.ArquivoNome,
		&i.ArquivoSha256,
		&i.Status,
		&i.Previa,
		&i.CriadaEm,
		&i.FinalizadaEm,
	)
	return i, err
}

const criarImportacao = `-- name: CriarImportacao :one
INSERT INTO importacoes (criada_por, arquivo_nome, arquivo_sha256, linhas, previa)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, status, criada_em
`

type CriarImportacaoParams struct {
	CriadaPor     int64
	ArquivoNome   string
	ArquivoSha256 string
	Linhas        []byte
	Previa        []byte
}

type CriarImportacaoRow struct {
	ID       int64
	Status   string
	CriadaEm time.Time
}

func (q *Queries) CriarImportacao(ctx context.Context, arg CriarImportacaoParams) (CriarImportacaoRow, error) {
	row := q.db.QueryRow(ctx, criarImportacao,
		arg.CriadaPor,
		arg.ArquivoNome,
		arg.ArquivoSha256,
		arg.Linhas,
		arg.Previa,
	)
	var i CriarImportacaoRow
	err := row.Scan(&i.ID, &i.Status, &i.CriadaEm)
	return i, err
}

const finalizarImportacao = `-- name: FinalizarImportacao :exec
UPDATE importacoes
SET status = $1, finalizada_em = now()
WHERE id = $2
`

type FinalizarImportacaoParams struct {
	Status string
	ID     int64
}

func (q *Queries) FinalizarImportacao(ctx context.Context, arg FinalizarImportacaoParams) error {
	_, err := q.db.Exec(ctx, finalizarImportacao, arg.Status, arg.ID)
	return err
}

const listarImportacoes = `-- name: ListarImportacoes :many
SELECT i.id, u.nome AS criada_por_nome, i.arquivo_nome, i.status,
       i.previa -> 'totais' AS totais, i.criada_em, i.finalizada_em
FROM importacoes i
JOIN usuarios u ON u.id = i.criada_por
ORDER BY i.criada_em DESC
LIMIT 20
`

type ListarImportacoesRow struct {
	ID            int64
	CriadaPorNome string
	ArquivoNome   string
	Status        string
	Totais        interface{}
	CriadaEm      time.Time
	FinalizadaEm  *time.Time
}

func (q *Queries) ListarImportacoes(ctx context.Context) ([]ListarImportacoesRow, error) {
	rows, err := q.db.Query(ctx, listarImportacoes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarImportacoesRow
	for rows.Next() {
		var i ListarImportacoesRow
		if err := rows.Scan(
			&i.ID,
			&i.CriadaPorNome,
			&i.ArquivoNome,
			&i.Status,
			&i.Totais,
			&i.CriadaEm,
			&i.FinalizadaEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const travarAplicacaoDeImportacoes = `-- name: TravarAplicacaoDeImportacoes :exec
SELECT pg_advisory_xact_lock(7301)
`

// Serializa aplicações de importação (duas ao mesmo tempo disputariam as mesmas cotas).
func (q *Queries) TravarAplicacaoDeImportacoes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, travarAplicacaoDeImportacoes)
	return err
}

const travarImportacao = `-- name: TravarImportacao :one
SELECT id, status, arquivo_nome, linhas, previa
FROM importacoes
WHERE id = $1
FOR UPDATE
`

type TravarImportacaoRow struct {
	ID          int64
	Status      string
	ArquivoNome string
	Linhas      []byte
	Previa      []byte
}

func (q *Queries) TravarImportacao(ctx context.Context, id int64) (TravarImportacaoRow, error) {
	row := q.db.QueryRow(ctx, travarImportacao, id)
	var i TravarImportacaoRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ArquivoNome,
		&i.Linhas,
		&i.Previa,
	)
	return i, err
}
