// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lances.sql

package db

import (
	"context"
	"time"
)

const buscarIntegracao = `-- name: BuscarIntegracao :one
SELECT nome, dados_cifrados, atualizado_em FROM integracoes WHERE nome = $1
`

func (q *Queries) BuscarIntegracao(ctx context.Context, nome string) (Integracao, error) {
	row := q.db.QueryRow(ctx, buscarIntegracao, nome)
	var i Integracao
	err := row.Scan(&i.Nome, &i.DadosCifrados, &i.AtualizadoEm)
	return i, err
}

const buscarLance = `-- name: BuscarLance :one
SELECT l.id, l.cota_id, l.protocolo, l.pdf_id, l.drive_status, q.cliente_id
FROM lances l JOIN cotas q ON q.id = l.cota_id
WHERE l.id = $1
`

type BuscarLanceRow struct {
	ID          int64
	CotaID      int64
	Protocolo   string
	PdfID       *string
	DriveStatus string
	ClienteID   int64
}

func (q *Queries) BuscarLance(ctx context.Context, id int64) (BuscarLanceRow, error) {
	row := q.db.QueryRow(ctx, buscarLance, id)
	var i BuscarLanceRow
	err := row.Scan(
		&i.ID,
		&i.CotaID,
		&i.Protocolo,
		&i.PdfID,
		&i.DriveStatus,
		&i.ClienteID,
	)
	return i, err
}

const dadosParaDrive = `-- name: DadosParaDrive :one
SELECT l.id, l.protocolo, COALESCE(l.registrado_em, l.criado_em)::timestamptz AS data_lance,
       q.grupo, q.cota, q.versao, c.nome AS cliente_nome, a.conteudo AS pdf
FROM lances l
JOIN cotas q ON q.id = l.cota_id
JOIN clientes c ON c.id = q.cliente_id
JOIN arquivos a ON a.id = l.pdf_id
WHERE l.id = $1
`

type DadosParaDriveRow struct {
	ID          int64
	Protocolo   string
	DataLance   time.Time
	Grupo       string
	Cota        string
	Versao      string
	ClienteNome string
	Pdf         []byte
}

func (q *Queries) DadosParaDrive(ctx context.Context, id int64) (DadosParaDriveRow, error) {
	row := q.db.QueryRow(ctx, dadosParaDrive, id)
	var i DadosParaDriveRow
	err := row.Scan(
		&i.ID,
		&i.Protocolo,
		&i.DataLance,
		&i.Grupo,
		&i.Cota,
		&i.Versao,
		&i.ClienteNome,
		&i.Pdf,
	)
	return i, err
}

const inserirLancePlataforma = `-- name: InserirLancePlataforma :one
INSERT INTO lances (cota_id, execucao_cota_id, origem, administradora, protocolo, assembleia_data, assembleia_numero,
                    modalidade, percentual, texto_protocolo, parcelas_em_atraso, lance_existente_autorizado,
                    pdf_id, drive_status, registrado_em)
VALUES ($1, $2, 'plataforma', $3, $4, $5,
        $6, $7, $8, $9,
        $10, $11, $12, $13, $14)
ON CONFLICT (administradora, protocolo) DO NOTHING
RETURNING id
`

type InserirLancePlataformaParams struct {
	CotaID                   int64
	ExecucaoCotaID           *int64
	Administradora           string
	Protocolo                string
	AssembleiaData           *time.Time
	AssembleiaNumero         *string
	Modalidade               string
	Percentual               *string
	TextoProtocolo           *string
	ParcelasEmAtraso         bool
	LanceExistenteAutorizado bool
	PdfID                    *string
	DriveStatus              string
	RegistradoEm             *time.Time
}

func (q *Queries) InserirLancePlataforma(ctx context.Context, arg InserirLancePlataformaParams) (int64, error) {
	row := q.db.QueryRow(ctx, inserirLancePlataforma,
		arg.CotaID,
		arg.ExecucaoCotaID,
		arg.Administradora,
		arg.Protocolo,
		arg.AssembleiaData,
		arg.AssembleiaNumero,
		arg.Modalidade,
		arg.Percentual,
		arg.TextoProtocolo,
		arg.ParcelasEmAtraso,
		arg.LanceExistenteAutorizado,
		arg.PdfID,
		arg.DriveStatus,
		arg.RegistradoEm,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lancesDaCotaNaAssembleia = `-- name: LancesDaCotaNaAssembleia :many
SELECT protocolo, origem FROM lances
WHERE cota_id = $1 AND assembleia_data = $2
ORDER BY registrado_em
`

type LancesDaCotaNaAssembleiaParams struct {
	CotaID         int64
	AssembleiaData *time.Time
}

type LancesDaCotaNaAssembleiaRow struct {
	Protocolo string
	Origem    string
}

func (q *Queries) LancesDaCotaNaAssembleia(ctx context.Context, arg LancesDaCotaNaAssembleiaParams) ([]LancesDaCotaNaAssembleiaRow, error) {
	rows, err := q.db.Query(ctx, lancesDaCotaNaAssembleia, arg.CotaID, arg.AssembleiaData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LancesDaCotaNaAssembleiaRow
	for rows.Next() {
		var i LancesDaCotaNaAssembleiaRow
		if err := rows.Scan(&i.Protocolo, &i.Origem); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarLancesDaExecucao = `-- name: ListarLancesDaExecucao :many
SELECT l.id, ec.id AS execucao_cota_id, l.protocolo, l.pdf_id, l.drive_status, l.drive_link, l.drive_erro, l.parcelas_em_atraso
FROM execucao_cotas ec
JOIN lances l ON l.cota_id = ec.cota_id
             AND (l.execucao_cota_id = ec.id OR (ec.status = 'reimpressa' AND l.protocolo = ec.protocolo))
WHERE ec.execucao_id = $1
`

type ListarLancesDaExecucaoRow struct {
	ID               int64
	ExecucaoCotaID   int64
	Protocolo        string
	PdfID            *string
	DriveStatus      string
	DriveLink        *string
	DriveErro        *string
	ParcelasEmAtraso bool
}

// Lances de uma execução: os que ela criou e, na reimpressão, o lance do protocolo
// reimpresso (que pode ter sido criado antes, por outra execução).
func (q *Queries) ListarLancesDaExecucao(ctx context.Context, execucaoID int64) ([]ListarLancesDaExecucaoRow, error) {
	rows, err := q.db.Query(ctx, listarLancesDaExecucao, execucaoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarLancesDaExecucaoRow
	for rows.Next() {
		var i ListarLancesDaExecucaoRow
		if err := rows.Scan(
			&i.ID,
			&i.ExecucaoCotaID,
			&i.Protocolo,
			&i.PdfID,
			&i.DriveStatus,
			&i.DriveLink,
			&i.DriveErro,
			&i.ParcelasEmAtraso,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarLancesDoCliente = `-- name: ListarLancesDoCliente :many
SELECT l.id, l.cota_id, q.grupo, q.cota, q.versao, l.origem, l.protocolo, l.assembleia_data, l.assembleia_numero,
       l.modalidade, l.percentual, l.parcelas_em_atraso, l.lance_existente_autorizado, l.pdf_id,
       l.drive_status, l.drive_link, l.drive_erro, l.registrado_em, ec.execucao_id
FROM lances l
JOIN cotas q ON q.id = l.cota_id
LEFT JOIN execucao_cotas ec ON ec.id = l.execucao_cota_id
WHERE q.cliente_id = $1
ORDER BY l.registrado_em DESC NULLS LAST, l.id DESC
`

type ListarLancesDoClienteRow struct {
	ID                       int64
	CotaID                   int64
	Grupo                    string
	Cota                     string
	Versao                   string
	Origem                   string
	Protocolo                string
	AssembleiaData           *time.Time
	AssembleiaNumero         *string
	Modalidade               string
	Percentual               *string
	ParcelasEmAtraso         bool
	LanceExistenteAutorizado bool
	PdfID                    *string
	DriveStatus              string
	DriveLink                *string
	DriveErro                *string
	RegistradoEm             *time.Time
	ExecucaoID               *int64
}

func (q *Queries) ListarLancesDoCliente(ctx context.Context, clienteID int64) ([]ListarLancesDoClienteRow, error) {
	rows, err := q.db.Query(ctx, listarLancesDoCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarLancesDoClienteRow
	for rows.Next() {
		var i ListarLancesDoClienteRow
		if err := rows.Scan(
			&i.ID,
			&i.CotaID,
			&i.Grupo,
			&i.Cota,
			&i.Versao,
			&i.Origem,
			&i.Protocolo,
			&i.AssembleiaData,
			&i.AssembleiaNumero,
			&i.Modalidade,
			&i.Percentual,
			&i.ParcelasEmAtraso,
			&i.LanceExistenteAutorizado,
			&i.PdfID,
			&i.DriveStatus,
			&i.DriveLink,
			&i.DriveErro,
			&i.RegistradoEm,
			&i.ExecucaoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarDriveEnviado = `-- name: MarcarDriveEnviado :exec
UPDATE lances
SET drive_status = 'enviado', drive_arquivo_id = $1, drive_link = $2, drive_erro = NULL, atualizado_em = now()
WHERE id = $3
`

type MarcarDriveEnviadoParams struct {
	DriveArquivoID *string
	DriveLink      *string
	ID             int64
}

func (q *Queries) MarcarDriveEnviado(ctx context.Context, arg MarcarDriveEnviadoParams) error {
	_, err := q.db.Exec(ctx, marcarDriveEnviado, arg.DriveArquivoID, arg.DriveLink, arg.ID)
	return err
}

const marcarDriveErro = `-- name: MarcarDriveErro :exec
UPDATE lances SET drive_status = 'erro', drive_erro = $1, atualizado_em = now() WHERE id = $2
`

type MarcarDriveErroParams struct {
	DriveErro *string
	ID        int64
}

func (q *Queries) MarcarDriveErro(ctx context.Context, arg MarcarDriveErroParams) error {
	_, err := q.db.Exec(ctx, marcarDriveErro, arg.DriveErro, arg.ID)
	return err
}

const recuperarEnviosTravados = `-- name: RecuperarEnviosTravados :execrows

UPDATE lances SET drive_status = 'pendente', atualizado_em = now()
WHERE drive_status = 'enviando' AND atualizado_em < now() - interval '10 minutes'
`

// ===== Fila de envio ao Google Drive =====
// Envio interrompido (API caiu no meio): volta para a fila.
func (q *Queries) RecuperarEnviosTravados(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recuperarEnviosTravados)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reenviarAoDrive = `-- name: ReenviarAoDrive :execrows
UPDATE lances SET drive_status = 'pendente', drive_tentativas = 0, drive_erro = NULL, atualizado_em = now()
WHERE id = $1 AND pdf_id IS NOT NULL AND drive_status IN ('erro', 'nao_enviar')
`

// Pedido na tela: tentar de novo depois de erro, ou enviar um comprovante que ficou sem envio.
func (q *Queries) ReenviarAoDrive(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, reenviarAoDrive, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const registrarComprovanteDoHistorico = `-- name: RegistrarComprovanteDoHistorico :one
INSERT INTO lances (cota_id, execucao_cota_id, origem, administradora, protocolo, assembleia_data, modalidade,
                    percentual, pdf_id, drive_status, registrado_em)
VALUES ($1, $2, 'historico', $3, $4, $5,
        $6, $7, $8, $9, $10)
ON CONFLICT (administradora, protocolo) DO UPDATE
SET pdf_id        = EXCLUDED.pdf_id,
    drive_status  = CASE WHEN lances.drive_status IN ('enviado', 'enviando') THEN lances.drive_status ELSE EXCLUDED.drive_status END,
    atualizado_em = now()
RETURNING id, origem
`

type RegistrarComprovanteDoHistoricoParams struct {
	CotaID         int64
	ExecucaoCotaID *int64
	Administradora string
	Protocolo      string
	AssembleiaData *time.Time
	Modalidade     string
	Percentual     *string
	PdfID          *string
	DriveStatus    string
	RegistradoEm   *time.Time
}

type RegistrarComprovanteDoHistoricoRow struct {
	ID     int64
	Origem string
}

// Reimpressão pelo Histórico: cria o lance (origem historico) ou anexa o PDF a um lance
// que já existe (ex.: registrado pela plataforma com o PDF pendente).
func (q *Queries) RegistrarComprovanteDoHistorico(ctx context.Context, arg RegistrarComprovanteDoHistoricoParams) (RegistrarComprovanteDoHistoricoRow, error) {
	row := q.db.QueryRow(ctx, registrarComprovanteDoHistorico,
		arg.CotaID,
		arg.ExecucaoCotaID,
		arg.Administradora,
		arg.Protocolo,
		arg.AssembleiaData,
		arg.Modalidade,
		arg.Percentual,
		arg.PdfID,
		arg.DriveStatus,
		arg.RegistradoEm,
	)
	var i RegistrarComprovanteDoHistoricoRow
	err := row.Scan(&i.ID, &i.Origem)
	return i, err
}

const reservarLancesParaDrive = `-- name: ReservarLancesParaDrive :many
UPDATE lances
SET drive_status = 'enviando', drive_tentativas = drive_tentativas + 1, atualizado_em = now()
WHERE id IN (
    SELECT l.id FROM lances l
    WHERE l.pdf_id IS NOT NULL
      AND (l.drive_status = 'pendente'
           OR (l.drive_status = 'erro' AND l.drive_tentativas < 5
               AND l.atualizado_em < now() - make_interval(mins => power(2, l.drive_tentativas - 1)::int)))
    ORDER BY l.id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id
`

// Pendentes e erros com espera crescente (1, 2, 4, 8 min), até 5 tentativas.
func (q *Queries) ReservarLancesParaDrive(ctx context.Context, limite int32) ([]int64, error) {
	rows, err := q.db.Query(ctx, reservarLancesParaDrive, limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salvarIntegracao = `-- name: SalvarIntegracao :exec

INSERT INTO integracoes (nome, dados_cifrados) VALUES ($1, $2)
ON CONFLICT (nome) DO UPDATE SET dados_cifrados = EXCLUDED.dados_cifrados, atualizado_em = now()
`

type SalvarIntegracaoParams struct {
	Nome          string
	DadosCifrados []byte
}

// ===== Integrações =====
func (q *Queries) SalvarIntegracao(ctx context.Context, arg SalvarIntegracaoParams) error {
	_, err := q.db.Exec(ctx, salvarIntegracao, arg.Nome, arg.DadosCifrados)
	return err
}
