// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type PerfilUsuario string

const (
	PerfilUsuarioAdmin    PerfilUsuario = "admin"
	PerfilUsuarioOperador PerfilUsuario = "operador"
	PerfilUsuarioLeitura  PerfilUsuario = "leitura"
)

func (e *PerfilUsuario) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PerfilUsuario(s)
	case string:
		*e = PerfilUsuario(s)
	default:
		return fmt.Errorf("unsupported scan type for PerfilUsuario: %T", src)
	}
	return nil
}

type NullPerfilUsuario struct {
	PerfilUsuario PerfilUsuario
	Valid         bool // Valid is true if PerfilUsuario is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPerfilUsuario) Scan(value interface{}) error {
	if value == nil {
		ns.PerfilUsuario, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PerfilUsuario.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPerfilUsuario) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PerfilUsuario), nil
}

func (e PerfilUsuario) Valid() bool {
	switch e {
	case PerfilUsuarioAdmin,
		PerfilUsuarioOperador,
		PerfilUsuarioLeitura:
		return true
	}
	return false
}

type Auditoria struct {
	ID         int64
	UsuarioID  *int64
	Acao       string
	Entidade   *string
	EntidadeID *string
	Detalhes   []byte
	Ip         *string
	CriadoEm   time.Time
}

type Cliente struct {
	ID              int64
	Nome            string
	NomeNormalizado string
	Telefone        *string
	Email           *string
	Origem          string
	CriadoEm        time.Time
	AtualizadoEm    time.Time
}

type Cota struct {
	ID               int64
	ClienteID        int64
	Administradora   string
	Grupo            string
	Cota             string
	Versao           string
	TipoConsorcio    *string
	ModalidadePadrao string
	Ativa            bool
	DadosPlanilha    []byte
	ImportacaoID     *int64
	CriadoEm         time.Time
	AtualizadoEm     time.Time
}

type Importacao struct {
	ID            int64
	CriadaPor     int64
	ArquivoNome   string
	ArquivoSha256 string
	Status        string
	Linhas        []byte
	Previa        []byte
	CriadaEm      time.Time
	FinalizadaEm  *time.Time
}

type Sessao struct {
	TokenHash   []byte
	UsuarioID   int64
	CsrfToken   string
	CriadaEm    time.Time
	UltimoUsoEm time.Time
	Ip          *string
	UserAgent   *string
}

type Usuario struct {
	ID           int64
	Email        string
	Nome         string
	SenhaHash    string
	Perfil       PerfilUsuario
	Ativo        bool
	CriadoEm     time.Time
	AtualizadoEm time.Time
}
