// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type PerfilUsuario string

const (
	PerfilUsuarioAdmin    PerfilUsuario = "admin"
	PerfilUsuarioOperador PerfilUsuario = "operador"
	PerfilUsuarioLeitura  PerfilUsuario = "leitura"
)

func (e *PerfilUsuario) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PerfilUsuario(s)
	case string:
		*e = PerfilUsuario(s)
	default:
		return fmt.Errorf("unsupported scan type for PerfilUsuario: %T", src)
	}
	return nil
}

type NullPerfilUsuario struct {
	PerfilUsuario PerfilUsuario
	Valid         bool // Valid is true if PerfilUsuario is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPerfilUsuario) Scan(value interface{}) error {
	if value == nil {
		ns.PerfilUsuario, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PerfilUsuario.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPerfilUsuario) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PerfilUsuario), nil
}

func (e PerfilUsuario) Valid() bool {
	switch e {
	case PerfilUsuarioAdmin,
		PerfilUsuarioOperador,
		PerfilUsuarioLeitura:
		return true
	}
	return false
}

type Arquivo struct {
	ID          string
	Tipo        string
	Nome        string
	ContentType string
	Tamanho     int32
	Sha256      string
	Conteudo    []byte
	CriadoEm    time.Time
	ExpiraEm    *time.Time
}

type Auditoria struct {
	ID         int64
	UsuarioID  *int64
	Acao       string
	Entidade   *string
	EntidadeID *string
	Detalhes   []byte
	Ip         *string
	CriadoEm   time.Time
}

type CheckinConfiguracao struct {
	ID           bool
	GrupoJid     string
	GrupoNome    string
	AtualizadoEm time.Time
}

type CheckinEvento struct {
	ID         int64
	ChaveDedup string
	Origem     string
	Payload    []byte
	RecebidoEm time.Time
}

type CheckinMensagem struct {
	ID                 int64
	EventoID           int64
	DestinoJid         string
	Texto              string
	Status             string
	Tentativas         int32
	ProximaTentativaEm time.Time
	UltimoErro         *string
	EnviadaEm          *time.Time
	CriadaEm           time.Time
}

type Cliente struct {
	ID              int64
	Nome            string
	NomeNormalizado string
	Telefone        *string
	Email           *string
	Origem          string
	CriadoEm        time.Time
	AtualizadoEm    time.Time
}

type Cota struct {
	ID               int64
	ClienteID        int64
	Administradora   string
	Grupo            string
	Cota             string
	Versao           string
	TipoConsorcio    *string
	ModalidadePadrao string
	Ativa            bool
	DadosPlanilha    []byte
	ImportacaoID     *int64
	CriadoEm         time.Time
	AtualizadoEm     time.Time
}

type ExecucaoCota struct {
	ID                     int64
	ExecucaoID             int64
	CotaID                 int64
	Ordem                  int32
	Grupo                  string
	Cota                   string
	Versao                 string
	ClienteNome            string
	Modalidade             string
	Status                 string
	ErroTipo               *string
	Erro                   *string
	Detalhes               []byte
	ScreenshotID           *string
	Tentativas             int32
	IniciadaEm             *time.Time
	FinalizadaEm           *time.Time
	AssembleiaAprovada     *string
	PermitirLanceExistente bool
	Protocolo              *string
}

type ExecucaoEvento struct {
	ID             int64
	ExecucaoID     int64
	ExecucaoCotaID *int64
	Nivel          string
	Mensagem       string
	Dados          []byte
	CriadoEm       time.Time
}

type Execuco struct {
	ID                     int64
	Tipo                   string
	Status                 string
	Credencial             string
	CriadaPor              int64
	AprovadaPor            *int64
	CancelamentoSolicitado bool
	CanceladaPor           *int64
	Worker                 *string
	TravaAte               *time.Time
	Erro                   *string
	CriadaEm               time.Time
	IniciadaEm             *time.Time
	FinalizadaEm           *time.Time
	DryRunOrigemID         *int64
}

type Importacao struct {
	ID            int64
	CriadaPor     int64
	ArquivoNome   string
	ArquivoSha256 string
	Status        string
	Linhas        []byte
	Previa        []byte
	CriadaEm      time.Time
	FinalizadaEm  *time.Time
}

type Integracao struct {
	Nome          string
	DadosCifrados []byte
	AtualizadoEm  time.Time
}

type Lance struct {
	ID                       int64
	CotaID                   int64
	ExecucaoCotaID           *int64
	Origem                   string
	Administradora           string
	Protocolo                string
	AssembleiaData           *time.Time
	AssembleiaNumero         *string
	Modalidade               string
	Percentual               *string
	TextoProtocolo           *string
	ParcelasEmAtraso         bool
	LanceExistenteAutorizado bool
	PdfID                    *string
	DriveStatus              string
	DriveArquivoID           *string
	DriveLink                *string
	DriveErro                *string
	DriveTentativas          int32
	RegistradoEm             *time.Time
	CriadoEm                 time.Time
	AtualizadoEm             time.Time
}

type Sessao struct {
	TokenHash   []byte
	UsuarioID   int64
	CsrfToken   string
	CriadaEm    time.Time
	UltimoUsoEm time.Time
	Ip          *string
	UserAgent   *string
}

type Usuario struct {
	ID           int64
	Email        string
	Nome         string
	SenhaHash    string
	Perfil       PerfilUsuario
	Ativo        bool
	CriadoEm     time.Time
	AtualizadoEm time.Time
}
