// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: perfil.sql

package db

import (
	"context"
	"time"
)

const apagarCredencialDoUsuario = `-- name: ApagarCredencialDoUsuario :execrows
DELETE FROM credenciais_usuario
WHERE usuario_id = $1 AND credencial = $2
`

type ApagarCredencialDoUsuarioParams struct {
	UsuarioID  int64
	Credencial string
}

func (q *Queries) ApagarCredencialDoUsuario(ctx context.Context, arg ApagarCredencialDoUsuarioParams) (int64, error) {
	result, err := q.db.Exec(ctx, apagarCredencialDoUsuario, arg.UsuarioID, arg.Credencial)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const atualizarPerfil = `-- name: AtualizarPerfil :one
UPDATE usuarios
SET nome = $1,
    telefone = $2,
    cargo = $3,
    observacoes = $4,
    atualizado_em = now()
WHERE id = $5
RETURNING id, email, nome, perfil, ativo, telefone, cargo, observacoes, criado_em, atualizado_em
`

type AtualizarPerfilParams struct {
	Nome        string
	Telefone    *string
	Cargo       *string
	Observacoes *string
	ID          int64
}

type AtualizarPerfilRow struct {
	ID           int64
	Email        string
	Nome         string
	Perfil       PerfilUsuario
	Ativo        bool
	Telefone     *string
	Cargo        *string
	Observacoes  *string
	CriadoEm     time.Time
	AtualizadoEm time.Time
}

func (q *Queries) AtualizarPerfil(ctx context.Context, arg AtualizarPerfilParams) (AtualizarPerfilRow, error) {
	row := q.db.QueryRow(ctx, atualizarPerfil,
		arg.Nome,
		arg.Telefone,
		arg.Cargo,
		arg.Observacoes,
		arg.ID,
	)
	var i AtualizarPerfilRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nome,
		&i.Perfil,
		&i.Ativo,
		&i.Telefone,
		&i.Cargo,
		&i.Observacoes,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const buscarCredencialDoUsuario = `-- name: BuscarCredencialDoUsuario :one
SELECT dados_cifrados, dica, criado_em, atualizado_em
FROM credenciais_usuario
WHERE usuario_id = $1 AND credencial = $2
`

type BuscarCredencialDoUsuarioParams struct {
	UsuarioID  int64
	Credencial string
}

type BuscarCredencialDoUsuarioRow struct {
	DadosCifrados []byte
	Dica          string
	CriadoEm      time.Time
	AtualizadoEm  time.Time
}

func (q *Queries) BuscarCredencialDoUsuario(ctx context.Context, arg BuscarCredencialDoUsuarioParams) (BuscarCredencialDoUsuarioRow, error) {
	row := q.db.QueryRow(ctx, buscarCredencialDoUsuario, arg.UsuarioID, arg.Credencial)
	var i BuscarCredencialDoUsuarioRow
	err := row.Scan(
		&i.DadosCifrados,
		&i.Dica,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const buscarPerfil = `-- name: BuscarPerfil :one
SELECT id, email, nome, perfil, ativo, telefone, cargo, observacoes, criado_em, atualizado_em
FROM usuarios
WHERE id = $1
`

type BuscarPerfilRow struct {
	ID           int64
	Email        string
	Nome         string
	Perfil       PerfilUsuario
	Ativo        bool
	Telefone     *string
	Cargo        *string
	Observacoes  *string
	CriadoEm     time.Time
	AtualizadoEm time.Time
}

func (q *Queries) BuscarPerfil(ctx context.Context, id int64) (BuscarPerfilRow, error) {
	row := q.db.QueryRow(ctx, buscarPerfil, id)
	var i BuscarPerfilRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nome,
		&i.Perfil,
		&i.Ativo,
		&i.Telefone,
		&i.Cargo,
		&i.Observacoes,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const gravarCredencialDoUsuario = `-- name: GravarCredencialDoUsuario :one
INSERT INTO credenciais_usuario (usuario_id, credencial, dados_cifrados, dica)
VALUES ($1, $2, $3, $4)
ON CONFLICT (usuario_id, credencial) DO UPDATE
    SET dados_cifrados = EXCLUDED.dados_cifrados,
        dica = EXCLUDED.dica,
        atualizado_em = now()
RETURNING credencial, dica, criado_em, atualizado_em
`

type GravarCredencialDoUsuarioParams struct {
	UsuarioID     int64
	Credencial    string
	DadosCifrados []byte
	Dica          string
}

type GravarCredencialDoUsuarioRow struct {
	Credencial   string
	Dica         string
	CriadoEm     time.Time
	AtualizadoEm time.Time
}

func (q *Queries) GravarCredencialDoUsuario(ctx context.Context, arg GravarCredencialDoUsuarioParams) (GravarCredencialDoUsuarioRow, error) {
	row := q.db.QueryRow(ctx, gravarCredencialDoUsuario,
		arg.UsuarioID,
		arg.Credencial,
		arg.DadosCifrados,
		arg.Dica,
	)
	var i GravarCredencialDoUsuarioRow
	err := row.Scan(
		&i.Credencial,
		&i.Dica,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listarCredenciaisDoUsuario = `-- name: ListarCredenciaisDoUsuario :many
SELECT credencial, dica, criado_em, atualizado_em
FROM credenciais_usuario
WHERE usuario_id = $1
ORDER BY credencial
`

type ListarCredenciaisDoUsuarioRow struct {
	Credencial   string
	Dica         string
	CriadoEm     time.Time
	AtualizadoEm time.Time
}

func (q *Queries) ListarCredenciaisDoUsuario(ctx context.Context, usuarioID int64) ([]ListarCredenciaisDoUsuarioRow, error) {
	rows, err := q.db.Query(ctx, listarCredenciaisDoUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarCredenciaisDoUsuarioRow
	for rows.Next() {
		var i ListarCredenciaisDoUsuarioRow
		if err := rows.Scan(
			&i.Credencial,
			&i.Dica,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarUsuariosComCredencial = `-- name: ListarUsuariosComCredencial :many
SELECT u.id, u.email, u.nome, u.perfil, (c.usuario_id IS NOT NULL)::boolean AS cadastrada, c.atualizado_em
FROM usuarios u
LEFT JOIN credenciais_usuario c ON c.usuario_id = u.id AND c.credencial = $1
WHERE u.ativo
ORDER BY u.nome, u.email
`

type ListarUsuariosComCredencialRow struct {
	ID           int64
	Email        string
	Nome         string
	Perfil       PerfilUsuario
	Cadastrada   bool
	AtualizadoEm *time.Time
}

// Visão do admin: uma linha por usuário ativo, com ou sem a credencial (nunca o valor).
func (q *Queries) ListarUsuariosComCredencial(ctx context.Context, credencial string) ([]ListarUsuariosComCredencialRow, error) {
	rows, err := q.db.Query(ctx, listarUsuariosComCredencial, credencial)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarUsuariosComCredencialRow
	for rows.Next() {
		var i ListarUsuariosComCredencialRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Nome,
			&i.Perfil,
			&i.Cadastrada,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
