// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessoes.sql

package db

import (
	"context"
	"time"
)

const apagarSessao = `-- name: ApagarSessao :exec
DELETE FROM sessoes WHERE token_hash = $1
`

func (q *Queries) ApagarSessao(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, apagarSessao, tokenHash)
	return err
}

const apagarSessoesDoUsuario = `-- name: ApagarSessoesDoUsuario :execrows
DELETE FROM sessoes
WHERE usuario_id = (SELECT id FROM usuarios WHERE email = $1)
`

func (q *Queries) ApagarSessoesDoUsuario(ctx context.Context, email string) (int64, error) {
	result, err := q.db.Exec(ctx, apagarSessoesDoUsuario, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const apagarSessoesExpiradas = `-- name: ApagarSessoesExpiradas :execrows
DELETE FROM sessoes
WHERE criada_em <= $1 OR ultimo_uso_em <= $2
`

type ApagarSessoesExpiradasParams struct {
	CriadaApos time.Time
	UsadaApos  time.Time
}

func (q *Queries) ApagarSessoesExpiradas(ctx context.Context, arg ApagarSessoesExpiradasParams) (int64, error) {
	result, err := q.db.Exec(ctx, apagarSessoesExpiradas, arg.CriadaApos, arg.UsadaApos)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const buscarSessaoValida = `-- name: BuscarSessaoValida :one
SELECT s.usuario_id, s.csrf_token, s.ultimo_uso_em, u.email, u.nome, u.perfil
FROM sessoes s
JOIN usuarios u ON u.id = s.usuario_id
WHERE s.token_hash = $1
  AND u.ativo
  AND s.criada_em > $2
  AND s.ultimo_uso_em > $3
`

type BuscarSessaoValidaParams struct {
	TokenHash  []byte
	CriadaApos time.Time
	UsadaApos  time.Time
}

type BuscarSessaoValidaRow struct {
	UsuarioID   int64
	CsrfToken   string
	UltimoUsoEm time.Time
	Email       string
	Nome        string
	Perfil      PerfilUsuario
}

// Sessão válida: usuário ativo, criada depois de @criada_apos (limite de 7 dias)
// e usada depois de @usada_apos (limite de 12 h sem uso).
func (q *Queries) BuscarSessaoValida(ctx context.Context, arg BuscarSessaoValidaParams) (BuscarSessaoValidaRow, error) {
	row := q.db.QueryRow(ctx, buscarSessaoValida, arg.TokenHash, arg.CriadaApos, arg.UsadaApos)
	var i BuscarSessaoValidaRow
	err := row.Scan(
		&i.UsuarioID,
		&i.CsrfToken,
		&i.UltimoUsoEm,
		&i.Email,
		&i.Nome,
		&i.Perfil,
	)
	return i, err
}

const criarSessao = `-- name: CriarSessao :exec
INSERT INTO sessoes (token_hash, usuario_id, csrf_token, ip, user_agent)
VALUES ($1, $2, $3, $4, $5)
`

type CriarSessaoParams struct {
	TokenHash []byte
	UsuarioID int64
	CsrfToken string
	Ip        *string
	UserAgent *string
}

func (q *Queries) CriarSessao(ctx context.Context, arg CriarSessaoParams) error {
	_, err := q.db.Exec(ctx, criarSessao,
		arg.TokenHash,
		arg.UsuarioID,
		arg.CsrfToken,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const tocarSessao = `-- name: TocarSessao :exec
UPDATE sessoes SET ultimo_uso_em = now() WHERE token_hash = $1
`

func (q *Queries) TocarSessao(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, tocarSessao, tokenHash)
	return err
}
