// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuarios.sql

package db

import (
	"context"
	"time"
)

const atualizarSenhaUsuario = `-- name: AtualizarSenhaUsuario :execrows
UPDATE usuarios
SET senha_hash = $1, atualizado_em = now()
WHERE email = $2
`

type AtualizarSenhaUsuarioParams struct {
	SenhaHash string
	Email     string
}

func (q *Queries) AtualizarSenhaUsuario(ctx context.Context, arg AtualizarSenhaUsuarioParams) (int64, error) {
	result, err := q.db.Exec(ctx, atualizarSenhaUsuario, arg.SenhaHash, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const buscarUsuarioPorEmail = `-- name: BuscarUsuarioPorEmail :one
SELECT id, email, nome, senha_hash, perfil, ativo
FROM usuarios
WHERE email = $1
`

type BuscarUsuarioPorEmailRow struct {
	ID        int64
	Email     string
	Nome      string
	SenhaHash string
	Perfil    PerfilUsuario
	Ativo     bool
}

func (q *Queries) BuscarUsuarioPorEmail(ctx context.Context, email string) (BuscarUsuarioPorEmailRow, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorEmail, email)
	var i BuscarUsuarioPorEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nome,
		&i.SenhaHash,
		&i.Perfil,
		&i.Ativo,
	)
	return i, err
}

const criarUsuario = `-- name: CriarUsuario :one
INSERT INTO usuarios (email, nome, senha_hash, perfil)
VALUES ($1, $2, $3, $4)
RETURNING id, email, nome, perfil, ativo, criado_em
`

type CriarUsuarioParams struct {
	Email     string
	Nome      string
	SenhaHash string
	Perfil    PerfilUsuario
}

type CriarUsuarioRow struct {
	ID       int64
	Email    string
	Nome     string
	Perfil   PerfilUsuario
	Ativo    bool
	CriadoEm time.Time
}

func (q *Queries) CriarUsuario(ctx context.Context, arg CriarUsuarioParams) (CriarUsuarioRow, error) {
	row := q.db.QueryRow(ctx, criarUsuario,
		arg.Email,
		arg.Nome,
		arg.SenhaHash,
		arg.Perfil,
	)
	var i CriarUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nome,
		&i.Perfil,
		&i.Ativo,
		&i.CriadoEm,
	)
	return i, err
}

const definirUsuarioAtivo = `-- name: DefinirUsuarioAtivo :execrows
UPDATE usuarios
SET ativo = $1, atualizado_em = now()
WHERE email = $2
`

type DefinirUsuarioAtivoParams struct {
	Ativo bool
	Email string
}

func (q *Queries) DefinirUsuarioAtivo(ctx context.Context, arg DefinirUsuarioAtivoParams) (int64, error) {
	result, err := q.db.Exec(ctx, definirUsuarioAtivo, arg.Ativo, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarUsuarios = `-- name: ListarUsuarios :many
SELECT id, email, nome, perfil, ativo, criado_em
FROM usuarios
ORDER BY email
`

type ListarUsuariosRow struct {
	ID       int64
	Email    string
	Nome     string
	Perfil   PerfilUsuario
	Ativo    bool
	CriadoEm time.Time
}

func (q *Queries) ListarUsuarios(ctx context.Context) ([]ListarUsuariosRow, error) {
	rows, err := q.db.Query(ctx, listarUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarUsuariosRow
	for rows.Next() {
		var i ListarUsuariosRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Nome,
			&i.Perfil,
			&i.Ativo,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrarAuditoria = `-- name: RegistrarAuditoria :exec
INSERT INTO auditoria (usuario_id, acao, entidade, entidade_id, detalhes, ip)
VALUES ($1, $2, $3, $4, $5, $6)
`

type RegistrarAuditoriaParams struct {
	UsuarioID  *int64
	Acao       string
	Entidade   *string
	EntidadeID *string
	Detalhes   []byte
	Ip         *string
}

func (q *Queries) RegistrarAuditoria(ctx context.Context, arg RegistrarAuditoriaParams) error {
	_, err := q.db.Exec(ctx, registrarAuditoria,
		arg.UsuarioID,
		arg.Acao,
		arg.Entidade,
		arg.EntidadeID,
		arg.Detalhes,
		arg.Ip,
	)
	return err
}
