// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vigia.sql

package db

import (
	"context"
)

const vigiaCotasAposConfirmar = `-- name: VigiaCotasAposConfirmar :many
SELECT id, execucao_id, grupo, cota, versao, erro
FROM execucao_cotas
WHERE status = 'erro_apos_confirmar' AND iniciada_em > now() - interval '24 hours'
ORDER BY id
`

type VigiaCotasAposConfirmarRow struct {
	ID         int64
	ExecucaoID int64
	Grupo      string
	Cota       string
	Versao     string
	Erro       *string
}

// Cotas que clicaram em Confirmar e não tiveram resultado confirmado, nas últimas 24 h.
func (q *Queries) VigiaCotasAposConfirmar(ctx context.Context) ([]VigiaCotasAposConfirmarRow, error) {
	rows, err := q.db.Query(ctx, vigiaCotasAposConfirmar)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VigiaCotasAposConfirmarRow
	for rows.Next() {
		var i VigiaCotasAposConfirmarRow
		if err := rows.Scan(
			&i.ID,
			&i.ExecucaoID,
			&i.Grupo,
			&i.Cota,
			&i.Versao,
			&i.Erro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vigiaDrive = `-- name: VigiaDrive :one
SELECT (count(*) FILTER (WHERE drive_status = 'erro' AND drive_tentativas >= 5))::int AS desistidos,
       (count(*) FILTER (WHERE drive_status IN ('pendente', 'erro') AND drive_tentativas < 5
                           AND atualizado_em < now() - interval '1 hour'))::int     AS atrasados
FROM lances
`

type VigiaDriveRow struct {
	Desistidos int32
	Atrasados  int32
}

func (q *Queries) VigiaDrive(ctx context.Context) (VigiaDriveRow, error) {
	row := q.db.QueryRow(ctx, vigiaDrive)
	var i VigiaDriveRow
	err := row.Scan(&i.Desistidos, &i.Atrasados)
	return i, err
}

const vigiaFila = `-- name: VigiaFila :one

SELECT (count(*) FILTER (WHERE status = 'na_fila' AND criada_em < now() - interval '30 minutes'))::int     AS na_fila_antigas,
       (count(*) FILTER (WHERE status = 'em_andamento' AND trava_ate < now() - interval '5 minutes'))::int AS travas_vencidas
FROM execucoes
`

type VigiaFilaRow struct {
	NaFilaAntigas  int32
	TravasVencidas int32
}

// Checagens do vigia (alertas por e-mail).
func (q *Queries) VigiaFila(ctx context.Context) (VigiaFilaRow, error) {
	row := q.db.QueryRow(ctx, vigiaFila)
	var i VigiaFilaRow
	err := row.Scan(&i.NaFilaAntigas, &i.TravasVencidas)
	return i, err
}
